//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRO
    {
        public decimal ID_LIBRO { get; set; }
        public string TITULO { get; set; }
        public Nullable<System.DateTime> ANO { get; set; }
        public string GENERO { get; set; }
        public Nullable<decimal> NUMERO_PAGINAS { get; set; }
        public Nullable<decimal> ID_AUTOR { get; set; }
    
        public virtual AUTOR AUTOR { get; set; }
    }
}
